# Generated by Django 4.1.5 on 2023-02-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_music_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
    ]
