# Generated by Django 4.1.5 on 2023-02-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='license_exclisive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='music',
            name='license_mp3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='music',
            name='license_trackout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='music',
            name='license_unlimited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='music',
            name='license_wav',
            field=models.BooleanField(default=False),
        ),
    ]
