# Generated by Django 4.1.5 on 2023-02-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_music_license_exclisive_music_license_mp3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=2000)),
            ],
        ),
    ]
