# Generated by Django 4.1.5 on 2023-02-19 23:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
