# Generated by Django 4.1.5 on 2023-03-05 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_music_date_news_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beats',
            fields=[
                ('name', models.CharField(default='Жаль', max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(default='The best song in history of humanity', max_length=2000)),
                ('date', models.DateField(default=datetime.date.today)),
                ('license_mp3', models.BooleanField(default=False)),
                ('license_wav', models.BooleanField(default=False)),
                ('license_trackout', models.BooleanField(default=False)),
                ('license_unlimited', models.BooleanField(default=False)),
                ('license_exclisive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('name', models.CharField(default='Жаль', max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(default='The best song in history of humanity', max_length=2000)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.DeleteModel(
            name='Music',
        ),
        migrations.AlterField(
            model_name='links',
            name='link',
            field=models.CharField(default='https://vk.com/', max_length=2000),
        ),
        migrations.AlterField(
            model_name='links',
            name='name',
            field=models.CharField(default='VK', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.CharField(default='Ты думал здесь что-то будет?', max_length=2000),
        ),
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(default='NEW RELEASE! TODAY!', max_length=100, primary_key=True, serialize=False),
        ),
    ]
